# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cloud Annotations
email: bourdakos1@gmail.com
description: >-  # this means to ignore newlines until "baseurl:"
  Create custom machine learning models for mobile, IoT and web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bourdakos1
github_username:  bourdakos1

# Enable google analytics
google_analytics: UA-150231586-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Direct posts to specific url
collections:
  workshops:
    output: true
    permalink: /workshops/:path:output_ext
    sort_by: order
  guides:
    output: true
    permalink: /docs
    order:
      - getting-started.md
      - preparing-training-data.md
      - object-detection.md
      - classification.md
      - labeling-with-a-team.md
      - uploading-images-via-api.md
      - exporting-annotations-via-gui.md
      - exporting-annotations-via-api.md
      - training-overview.md
      - training-via-gui.md
      - installing-the-cli.md
      - training-via-cli.md
      - training-with-google-colab.md
      - non-interactive-training.md
      - custom-training-scripts.md
      - downloading-a-model-via-gui.md
      - downloading-a-model-via-cli.md
      - using-a-model.md
      - auto-labeling.md
      

# Theme pages
defaults:
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: workshop-stepper
  - scope:
      path: ""
      type: "guides"
    values:
      layout: guides
