language: go
go: 1.13.x
os: linux
dist: xenial

services:
- docker

before_install:
- wget https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip -O /tmp/protoc-3.0.0-linux-x86_64.zip
- unzip /tmp/protoc-3.0.0-linux-x86_64.zip -d /tmp/protoc-3.0.0
- export PATH=$PATH:/tmp/protoc-3.0.0/bin/

install:
- echo "" > trainer/.env # `make` expects an `.env` file, so create an empty one.
- pushd trainer
- make setup_classification
- make setup_object_detection
- popd

jobs:
  include:
    - stage: publish docs
      if: branch = master
      before_install: skip
      install: curl -sL https://ibm.biz/idt-installer | bash
      script: pushd docs && ./deploy.sh && popd
    - stage: test
      script: pushd trainer && make test_classification && popd
    - stage: test
      script: pushd trainer && make test_object_detection && popd
    - stage: deploy
      script: skip
      deploy:
      - provider: script
        skip_cleanup: true # keep the pulled model repos from install phase.
        script: ./release.sh
        on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux