apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app: docs
    tier: docs
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: docs
    tier: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  selector:
    matchLabels:
      app: docs
      tier: docs
  replicas: 3
  template:
    metadata:
      labels:
        app: docs
        tier: docs
    spec:
      containers:
      - name: docs
        image: us.icr.io/bourdakos1/docs:4e210023fdf7f243c9a4df33b3c98d3fc5c803f3
        ports:
        - containerPort: 8012
